/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: hacker2446 (https://sketchfab.com/hacker2446)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/corona-virus-778bf35d170c4bf38dcc6c6dc0339756
title: Corona virus
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.02, -0.06, 0.02]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group rotation={[0.54, 1.12, 0.3]} scale={[1.56, 1.56, 1.56]}>
              <mesh geometry={nodes.mesh_0.geometry} material={materials['Material.002']} />
              <mesh geometry={nodes.mesh_1.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.14, -1.47, 0.67]} rotation={[2.24, -1.44, -0.59]} scale={[0.3, 0.3, 0.3]}>
              <mesh geometry={nodes.mesh_2.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.29, -0.69, 1.35]} rotation={[-2.84, -1.31, 1.51]} scale={[0.3, 0.3, 0.3]}>
              <mesh geometry={nodes.mesh_3.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.86, -1.33, 0.45]} rotation={[-2.46, -0.78, 1.05]} scale={[0.29, 0.29, 0.29]}>
              <mesh geometry={nodes.mesh_4.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-1, -0.97, 0.74]} rotation={[-2.43, -0.7, 1.58]} scale={[0.3, 0.3, 0.3]}>
              <mesh geometry={nodes.mesh_5.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.32, -1.37, 0.21]} rotation={[1.09, -1.12, -2.05]} scale={[0.3, 0.3, 0.3]}>
              <mesh geometry={nodes.mesh_6.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.04, -1.27, 0.98]} rotation={[1.5, -1.37, -1.01]} scale={[0.37, 0.37, 0.37]}>
              <mesh geometry={nodes.mesh_7.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.23, -0.76, 1.34]} rotation={[1.17, -1.2, -0.89]} scale={[0.36, 0.36, 0.36]}>
              <mesh geometry={nodes.mesh_8.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.09, -0.42, 1.48]} rotation={[1.28, -1.29, -0.5]} scale={[0.31, 0.31, 0.31]}>
              <mesh geometry={nodes.mesh_9.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.22, -0.12, 1.51]} rotation={[3.09, -1.4, 1.48]} scale={[0.36, 0.36, 0.36]}>
              <mesh geometry={nodes.mesh_10.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.72, -0.41, 1.17]} rotation={[-2.49, -0.9, 1.9]} scale={[0.3, 0.3, 0.3]}>
              <mesh geometry={nodes.mesh_11.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-1.08, -0.2, 0.85]} rotation={[-2.4, -0.53, 1.87]} scale={[0.37, 0.37, 0.37]}>
              <mesh geometry={nodes.mesh_12.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-1.17, -0.32, 0.67]} rotation={[-2.38, -0.43, 1.77]} scale={[0.29, 0.29, 0.29]}>
              <mesh geometry={nodes.mesh_13.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-1.2, -0.77, 0.35]} rotation={[-2.37, -0.36, 1.45]} scale={[0.29, 0.29, 0.29]}>
              <mesh geometry={nodes.mesh_14.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.79, -1.23, -0.24]} rotation={[-2.38, -0.4, 0.57]} scale={[0.32, 0.32, 0.32]}>
              <mesh geometry={nodes.mesh_15.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.59, -1.4, -0.01]} rotation={[-2.47, -0.84, 0.49]} scale={[0.37, 0.37, 0.37]}>
              <mesh geometry={nodes.mesh_16.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.12, -1.48, 0.28]} rotation={[2.4, -1.44, -0.77]} scale={[0.29, 0.29, 0.29]}>
              <mesh geometry={nodes.mesh_17.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-1.17, -0.04, -0.51]} rotation={[-2.28, 0.3, 1.25]} scale={[0.33, 0.33, 0.33]}>
              <mesh geometry={nodes.mesh_18.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-1.21, 0.45, -0.24]} rotation={[-2.27, 0.4, 1.52]} scale={[0.36, 0.36, 0.36]}>
              <mesh geometry={nodes.mesh_19.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-1.15, 0.33, -0.51]} rotation={[-2.26, 0.46, 1.39]} scale={[0.36, 0.36, 0.36]}>
              <mesh geometry={nodes.mesh_20.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-1, 0.84, -0.32]} rotation={[-2.22, 0.69, 1.59]} scale={[0.31, 0.31, 0.31]}>
              <mesh geometry={nodes.mesh_21.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-1.13, -0.79, -0.25]} rotation={[-2.33, -0.08, 1.01]} scale={[0.34, 0.34, 0.34]}>
              <mesh geometry={nodes.mesh_22.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-1.3, -0.26, -0.1]} rotation={[-2.32, 0.04, 1.39]} scale={[0.37, 0.37, 0.37]}>
              <mesh geometry={nodes.mesh_23.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-1.32, 0.11, 0.2]} rotation={[-2.32, 0.01, 1.62]} scale={[0.37, 0.37, 0.37]}>
              <mesh geometry={nodes.mesh_24.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-1.18, 0.28, 0.78]} rotation={[-2.37, -0.32, 1.9]} scale={[0.32, 0.32, 0.32]}>
              <mesh geometry={nodes.mesh_25.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-1.16, 0.85, 0.52]} rotation={[-2.29, 0.23, 1.99]} scale={[0.35, 0.35, 0.35]}>
              <mesh geometry={nodes.mesh_26.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-1.2, 0.64, 0.64]} rotation={[-2.33, -0.02, 1.96]} scale={[0.33, 0.33, 0.33]}>
              <mesh geometry={nodes.mesh_27.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.87, 1.15, -0.02]} rotation={[-2.17, 0.85, 1.79]} scale={[0.31, 0.31, 0.31]}>
              <mesh geometry={nodes.mesh_28.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.65, 1.25, -0.15]} rotation={[-2.09, 1.06, 1.72]} scale={[0.37, 0.37, 0.37]}>
              <mesh geometry={nodes.mesh_29.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.77, 0.74, -0.8]} rotation={[-2.18, 0.82, 1.4]} scale={[0.33, 0.33, 0.33]}>
              <mesh geometry={nodes.mesh_30.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.75, 0.49, -0.96]} rotation={[-2.2, 0.76, 1.21]} scale={[0.32, 0.32, 0.32]}>
              <mesh geometry={nodes.mesh_31.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.41, 0.07, -1.31]} rotation={[-2.18, 0.84, 0.67]} scale={[0.3, 0.3, 0.3]}>
              <mesh geometry={nodes.mesh_32.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.81, -0.25, -0.99]} rotation={[-2.26, 0.47, 0.8]} scale={[0.31, 0.31, 0.31]}>
              <mesh geometry={nodes.mesh_33.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.93, -0.5, -0.77]} rotation={[-2.29, 0.25, 0.81]} scale={[0.33, 0.33, 0.33]}>
              <mesh geometry={nodes.mesh_34.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.32, 1.05, -1.17]} rotation={[-0.52, 1.44, -0.23]} scale={[0.37, 0.37, 0.37]}>
              <mesh geometry={nodes.mesh_35.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.12, 1.24, -0.77]} rotation={[-1.06, 1.43, 0.63]} scale={[0.32, 0.32, 0.32]}>
              <mesh geometry={nodes.mesh_36.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.93, 1.01, -0.91]} rotation={[0.64, 0.93, -1.33]} scale={[0.37, 0.37, 0.37]}>
              <mesh geometry={nodes.mesh_37.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.94, 1.23, -0.19]} rotation={[0.67, 0.82, -0.91]} scale={[0.33, 0.33, 0.33]}>
              <mesh geometry={nodes.mesh_38.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.14, 0.42, -1.46]} rotation={[-1.78, 1.32, 0.29]} scale={[0.35, 0.35, 0.35]}>
              <mesh geometry={nodes.mesh_39.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.02, 0.89, -1.23]} rotation={[-1.88, 1.27, 0.97]} scale={[0.34, 0.34, 0.34]}>
              <mesh geometry={nodes.mesh_40.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.1, 1.16, -0.86]} rotation={[-1.8, 1.31, 1.27]} scale={[0.33, 0.33, 0.33]}>
              <mesh geometry={nodes.mesh_41.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.15, 1.35, -0.33]} rotation={[-1.49, 1.39, 1.22]} scale={[0.34, 0.34, 0.34]}>
              <mesh geometry={nodes.mesh_42.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.13, 1.33, -0.49]} rotation={[-0.56, 1.44, 0.28]} scale={[0.35, 0.35, 0.35]}>
              <mesh geometry={nodes.mesh_43.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.57, 1.36, -0.1]} rotation={[0.57, 1.08, -0.68]} scale={[0.36, 0.36, 0.36]}>
              <mesh geometry={nodes.mesh_44.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.96, 1.23, 0.08]} rotation={[0.71, 0.66, -0.82]} scale={[0.33, 0.33, 0.33]}>
              <mesh geometry={nodes.mesh_45.geometry} material={materials['Material.002']} />
            </group>
            <group position={[1.34, 0.7, -0.29]} rotation={[0.78, 0.27, -1.4]} scale={[0.37, 0.37, 0.37]}>
              <mesh geometry={nodes.mesh_46.geometry} material={materials['Material.002']} />
            </group>
            <group position={[1.21, 0.8, -0.74]} rotation={[0.73, 0.6, -1.52]} scale={[0.35, 0.35, 0.35]}>
              <mesh geometry={nodes.mesh_47.geometry} material={materials['Material.002']} />
            </group>
            <group position={[1.17, 0.01, -0.82]} rotation={[0.79, 0.23, -2.12]} scale={[0.34, 0.34, 0.34]}>
              <mesh geometry={nodes.mesh_48.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.95, 0.21, -1.13]} rotation={[0.72, 0.63, -2.19]} scale={[0.33, 0.33, 0.33]}>
              <mesh geometry={nodes.mesh_49.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.36, 0.54, -1.43]} rotation={[-0.47, 1.43, -0.92]} scale={[0.34, 0.34, 0.34]}>
              <mesh geometry={nodes.mesh_50.geometry} material={materials['Material.002']} />
            </group>
            <group position={[1.21, -0.49, 0.09]} rotation={[0.87, -0.36, -1.75]} scale={[0.31, 0.31, 0.31]}>
              <mesh geometry={nodes.mesh_51.geometry} material={materials['Material.002']} />
            </group>
            <group position={[1.22, -0.23, 0.44]} rotation={[0.87, -0.38, -1.45]} scale={[0.34, 0.34, 0.34]}>
              <mesh geometry={nodes.mesh_52.geometry} material={materials['Material.002']} />
            </group>
            <group position={[1.16, -0.54, 0.27]} rotation={[0.88, -0.44, -1.67]} scale={[0.3, 0.3, 0.3]}>
              <mesh geometry={nodes.mesh_53.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.89, -0.26, 0.98]} rotation={[0.9, -0.57, -1.14]} scale={[0.35, 0.35, 0.35]}>
              <mesh geometry={nodes.mesh_54.geometry} material={materials['Material.002']} />
            </group>
            <group position={[1.26, -0.18, -0.48]} rotation={[0.82, -0.02, -1.98]} scale={[0.33, 0.33, 0.33]}>
              <mesh geometry={nodes.mesh_55.geometry} material={materials['Material.002']} />
            </group>
            <group position={[1.36, 0.25, -0.37]} rotation={[0.81, 0.08, -1.7]} scale={[0.35, 0.35, 0.35]}>
              <mesh geometry={nodes.mesh_56.geometry} material={materials['Material.002']} />
            </group>
            <group position={[1.23, 0.52, 0.43]} rotation={[0.84, -0.16, -1.12]} scale={[0.34, 0.34, 0.34]}>
              <mesh geometry={nodes.mesh_57.geometry} material={materials['Material.002']} />
            </group>
            <group position={[1.05, 0.79, 0.56]} rotation={[0.83, -0.1, -0.86]} scale={[0.31, 0.31, 0.31]}>
              <mesh geometry={nodes.mesh_58.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.96, 0.46, 0.81]} rotation={[0.86, -0.32, -0.89]} scale={[0.35, 0.35, 0.35]}>
              <mesh geometry={nodes.mesh_59.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.63, 0.23, 1.19]} rotation={[0.9, -0.54, -0.73]} scale={[0.33, 0.33, 0.33]}>
              <mesh geometry={nodes.mesh_60.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.36, -0.56, 1.4]} rotation={[1.03, -1.02, -0.91]} scale={[0.33, 0.33, 0.33]}>
              <mesh geometry={nodes.mesh_61.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.72, -0.56, 1.07]} rotation={[0.94, -0.74, -1.21]} scale={[0.37, 0.37, 0.37]}>
              <mesh geometry={nodes.mesh_62.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.72, -1.03, 0.59]} rotation={[0.96, -0.83, -1.7]} scale={[0.31, 0.31, 0.31]}>
              <mesh geometry={nodes.mesh_63.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.67, -1.13, 0.48]} rotation={[0.97, -0.87, -1.82]} scale={[0.35, 0.35, 0.35]}>
              <mesh geometry={nodes.mesh_64.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.97, -0.88, 0.23]} rotation={[0.91, -0.61, -1.86]} scale={[0.33, 0.33, 0.33]}>
              <mesh geometry={nodes.mesh_65.geometry} material={materials['Material.002']} />
            </group>
            <group position={[1.14, -0.58, -0.24]} rotation={[0.86, -0.29, -2.02]} scale={[0.3, 0.3, 0.3]}>
              <mesh geometry={nodes.mesh_66.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.41, -0.92, -0.84]} rotation={[-2.33, -0.01, 0.25]} scale={[0.37, 0.37, 0.37]}>
              <mesh geometry={nodes.mesh_67.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.24, -0.63, -1.1]} rotation={[0.36, 1.28, -2.52]} scale={[0.35, 0.35, 0.35]}>
              <mesh geometry={nodes.mesh_68.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.19, -1.17, -0.53]} rotation={[1.33, -1.31, -2.33]} scale={[0.29, 0.29, 0.29]}>
              <mesh geometry={nodes.mesh_69.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.52, -0.88, -0.79]} rotation={[0.86, -0.3, -2.74]} scale={[0.36, 0.36, 0.36]}>
              <mesh geometry={nodes.mesh_70.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.61, -0.98, -0.69]} rotation={[-2.34, -0.11, 0.41]} scale={[0.29, 0.29, 0.29]}>
              <mesh geometry={nodes.mesh_71.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.54, -0.69, -0.96]} rotation={[-2.29, 0.28, 0.41]} scale={[0.36, 0.36, 0.36]}>
              <mesh geometry={nodes.mesh_72.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.15, -0.4, -1.25]} rotation={[-2.16, 0.9, 0.21]} scale={[0.37, 0.37, 0.37]}>
              <mesh geometry={nodes.mesh_73.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.29, -0.18, -1.29]} rotation={[-2.17, 0.86, 0.44]} scale={[0.35, 0.35, 0.35]}>
              <mesh geometry={nodes.mesh_74.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.42, 0.14, -1.41]} rotation={[0.18, 1.35, -1.93]} scale={[0.34, 0.34, 0.34]}>
              <mesh geometry={nodes.mesh_75.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.23, 0.13, -1.43]} rotation={[-1.44, 1.4, -0.3]} scale={[0.33, 0.33, 0.33]}>
              <mesh geometry={nodes.mesh_76.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.82, -0.25, -1.06]} rotation={[0.75, 0.46, -2.48]} scale={[0.32, 0.32, 0.32]}>
              <mesh geometry={nodes.mesh_77.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.94, -0.49, -0.8]} rotation={[0.81, 0.07, -2.42]} scale={[0.36, 0.36, 0.36]}>
              <mesh geometry={nodes.mesh_78.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.97, -0.81, -0.41]} rotation={[0.87, -0.36, -2.28]} scale={[0.37, 0.37, 0.37]}>
              <mesh geometry={nodes.mesh_79.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.73, -0.93, -0.57]} rotation={[0.88, -0.43, -2.51]} scale={[0.34, 0.34, 0.34]}>
              <mesh geometry={nodes.mesh_80.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.44, -1.32, 0.21]} rotation={[1.04, -1.03, -2.06]} scale={[0.29, 0.29, 0.29]}>
              <mesh geometry={nodes.mesh_81.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.06, -1.37, -0.13]} rotation={[1.68, -1.4, -1.77]} scale={[0.35, 0.35, 0.35]}>
              <mesh geometry={nodes.mesh_82.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.43, -1.2, -0.46]} rotation={[-2.41, -0.6, 0.27]} scale={[0.35, 0.35, 0.35]}>
              <mesh geometry={nodes.mesh_83.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.47, 1.3, 0.82]} rotation={[-1.99, 1.19, 2.47]} scale={[0.35, 0.35, 0.35]}>
              <mesh geometry={nodes.mesh_84.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.63, 1.13, 1.01]} rotation={[-2.3, 0.19, 2.77]} scale={[0.31, 0.31, 0.31]}>
              <mesh geometry={nodes.mesh_85.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.1, 1.08, 1]} rotation={[0.82, 0.01, -0.21]} scale={[0.38, 0.38, 0.38]}>
              <mesh geometry={nodes.mesh_86.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.33, 0.93, 1.23]} rotation={[1.27, -1.28, 0.27]} scale={[0.37, 0.37, 0.37]}>
              <mesh geometry={nodes.mesh_87.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.58, 1.38, 0.23]} rotation={[-2.02, 1.16, 1.91]} scale={[0.35, 0.35, 0.35]}>
              <mesh geometry={nodes.mesh_88.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.79, 1.28, 0.38]} rotation={[-2.16, 0.88, 2.09]} scale={[0.3, 0.3, 0.3]}>
              <mesh geometry={nodes.mesh_89.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.9, 1.15, 0.77]} rotation={[-2.27, 0.4, 2.39]} scale={[0.32, 0.32, 0.32]}>
              <mesh geometry={nodes.mesh_90.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-1.09, 0.29, 0.91]} rotation={[-2.38, -0.43, 1.98]} scale={[0.37, 0.37, 0.37]}>
              <mesh geometry={nodes.mesh_91.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.77, 0.44, 1.22]} rotation={[-2.45, -0.76, 2.27]} scale={[0.3, 0.3, 0.3]}>
              <mesh geometry={nodes.mesh_92.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.46, 0.07, 1.42]} rotation={[-2.64, -1.17, 2.05]} scale={[0.29, 0.29, 0.29]}>
              <mesh geometry={nodes.mesh_93.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.2, -0.12, 1.5]} rotation={[1.06, -1.06, -0.56]} scale={[0.34, 0.34, 0.34]}>
              <mesh geometry={nodes.mesh_94.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.25, 0.33, 1.37]} rotation={[0.95, -0.78, -0.46]} scale={[0.34, 0.34, 0.34]}>
              <mesh geometry={nodes.mesh_95.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.71, 0.83, 0.86]} rotation={[0.84, -0.19, -0.6]} scale={[0.38, 0.38, 0.38]}>
              <mesh geometry={nodes.mesh_96.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.9, 0.85, 0.72]} rotation={[0.84, -0.15, -0.71]} scale={[0.32, 0.32, 0.32]}>
              <mesh geometry={nodes.mesh_97.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.26, 1.36, 0.58]} rotation={[0.67, 0.83, -0.36]} scale={[0.29, 0.29, 0.29]}>
              <mesh geometry={nodes.mesh_98.geometry} material={materials['Material.002']} />
            </group>
            <group rotation={[0.54, 1.12, -1.27]} scale={[0.29, 0.29, 0.29]}>
              <mesh geometry={nodes.mesh_99.geometry} material={materials['Material.002']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
